# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Файловая статистика.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(398, 276)
        MainWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStatusTip("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 361, 201))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filename_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.filename_lbl.setObjectName("filename_lbl")
        self.horizontalLayout.addWidget(self.filename_lbl)
        self.filenameEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.filenameEdit.setObjectName("filenameEdit")
        self.horizontalLayout.addWidget(self.filenameEdit)
        self.button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.button.setObjectName("button")
        self.horizontalLayout.addWidget(self.button)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.min_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.min_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.min_lbl.setObjectName("min_lbl")
        self.verticalLayout_2.addWidget(self.min_lbl)
        self.avg_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.avg_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.avg_lbl.setObjectName("avg_lbl")
        self.verticalLayout_2.addWidget(self.avg_lbl)
        self.max_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.max_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.max_lbl.setObjectName("max_lbl")
        self.verticalLayout_2.addWidget(self.max_lbl)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.minEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.minEdit.setObjectName("minEdit")
        self.verticalLayout_3.addWidget(self.minEdit)
        self.maxEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.maxEdit.setObjectName("maxEdit")
        self.verticalLayout_3.addWidget(self.maxEdit)
        self.avgEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.avgEdit.setObjectName("avgEdit")
        self.verticalLayout_3.addWidget(self.avgEdit)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 398, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.filename_lbl.setText(_translate("MainWindow", "Имя файла:"))
        self.button.setText(_translate("MainWindow", "Расчитать"))
        self.min_lbl.setText(_translate("MainWindow", "Минимальное значение:"))
        self.avg_lbl.setText(_translate("MainWindow", "Среднее значение:"))
        self.max_lbl.setText(_translate("MainWindow", "Максимальное значение:"))
