# Form implementation generated from reading ui file 'about_book_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(368, 492)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 30, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_for_image = QtWidgets.QLabel(parent=Dialog)
        self.lbl_for_image.setMinimumSize(QtCore.QSize(200, 200))
        self.lbl_for_image.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lbl_for_image.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lbl_for_image.setText("")
        self.lbl_for_image.setScaledContents(True)
        self.lbl_for_image.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_for_image.setObjectName("lbl_for_image")
        self.horizontalLayout.addWidget(self.lbl_for_image)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lbl_book_nameS = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        self.lbl_book_nameS.setFont(font)
        self.lbl_book_nameS.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_book_nameS.setObjectName("lbl_book_nameS")
        self.verticalLayout.addWidget(self.lbl_book_nameS)
        self.lbl_book_name = QtWidgets.QLabel(parent=Dialog)
        self.lbl_book_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_book_name.setObjectName("lbl_book_name")
        self.verticalLayout.addWidget(self.lbl_book_name)
        self.lbl_book_authorS = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        self.lbl_book_authorS.setFont(font)
        self.lbl_book_authorS.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_book_authorS.setObjectName("lbl_book_authorS")
        self.verticalLayout.addWidget(self.lbl_book_authorS)
        self.lbl_book_author = QtWidgets.QLabel(parent=Dialog)
        self.lbl_book_author.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_book_author.setObjectName("lbl_book_author")
        self.verticalLayout.addWidget(self.lbl_book_author)
        self.lbl_book_yearS = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        self.lbl_book_yearS.setFont(font)
        self.lbl_book_yearS.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_book_yearS.setObjectName("lbl_book_yearS")
        self.verticalLayout.addWidget(self.lbl_book_yearS)
        self.lbl_book_year = QtWidgets.QLabel(parent=Dialog)
        self.lbl_book_year.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_book_year.setObjectName("lbl_book_year")
        self.verticalLayout.addWidget(self.lbl_book_year)
        self.lbl_book_genreS = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        self.lbl_book_genreS.setFont(font)
        self.lbl_book_genreS.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_book_genreS.setObjectName("lbl_book_genreS")
        self.verticalLayout.addWidget(self.lbl_book_genreS)
        self.lbl_book_genre = QtWidgets.QLabel(parent=Dialog)
        self.lbl_book_genre.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_book_genre.setObjectName("lbl_book_genre")
        self.verticalLayout.addWidget(self.lbl_book_genre)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Информация о книге"))
        self.lbl_book_nameS.setText(_translate("Dialog", "Название"))
        self.lbl_book_name.setText(_translate("Dialog", "Название книги"))
        self.lbl_book_authorS.setText(_translate("Dialog", "Автор"))
        self.lbl_book_author.setText(_translate("Dialog", "Автор"))
        self.lbl_book_yearS.setText(_translate("Dialog", "Год выпуска"))
        self.lbl_book_year.setText(_translate("Dialog", "Год выпуска"))
        self.lbl_book_genreS.setText(_translate("Dialog", "Жанр"))
        self.lbl_book_genre.setText(_translate("Dialog", "Жанр"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
