# Form implementation generated from reading ui file 'w_create_theory.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys

from PyQt6.QtWidgets import QDialog


class Window_for_create_theory(QDialog):
    def __init__(self):
        super().__init__()

        self.setObjectName("Dialog")
        self.resize(651, 485)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.save_article = QtWidgets.QPushButton(self)
        self.save_article.setMinimumSize(QtCore.QSize(130, 30))
        self.save_article.setObjectName("save_article")
        self.save_article.clicked.connect(self.accept)

        self.horizontalLayout.addWidget(self.save_article)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Введите тему"))
        self.plainTextEdit.setPlaceholderText(_translate("Dialog", "Ваш текст здесь..."))
        self.save_article.setText(_translate("Dialog", "Сохранить"))

    def get_article_info(self):
        '''Обработка и запись в файл
        передача инфы в файл с логикой'''
        return self.lineEdit.text(), self.plainTextEdit.toPlainText()
