# Form implementation generated from reading ui file 'Окно авторизации.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox, QDialog


class Auth_form(QDialog):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(345, 255)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 308, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(40, -1, 40, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_login = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.lbl_login.setMaximumSize(QtCore.QSize(70, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_login.setFont(font)
        self.lbl_login.setObjectName("lbl_login")
        self.horizontalLayout.addWidget(self.lbl_login)
        self.lineE_login = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineE_login.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineE_login.setObjectName("lineE_login")
        self.horizontalLayout.addWidget(self.lineE_login)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(30, -1, 35, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_password = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.lbl_password.setMaximumSize(QtCore.QSize(70, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_password.setFont(font)
        self.lbl_password.setObjectName("lbl_password")
        self.horizontalLayout_2.addWidget(self.lbl_password)
        self.lineE_password = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineE_password.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineE_password.setObjectName("lineE_pasword")
        self.horizontalLayout_2.addWidget(self.lineE_password)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_enter = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_enter.sizePolicy().hasHeightForWidth())
        self.btn_enter.setSizePolicy(sizePolicy)
        self.btn_enter.setMinimumSize(QtCore.QSize(0, 5))
        self.btn_enter.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_enter.setFont(font)
        self.btn_enter.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_enter.setDefault(False)
        self.btn_enter.setObjectName("btn_enter")
        self.horizontalLayout_3.addWidget(self.btn_enter)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.btn_registration = QtWidgets.QPushButton(parent=Form)
        self.btn_registration.setGeometry(QtCore.QRect(20, 230, 75, 20))
        self.btn_registration.setMaximumSize(QtCore.QSize(16777215, 20))
        self.btn_registration.setFlat(True)
        self.btn_registration.setObjectName("btn_registration")

        self.btn_enter.clicked.connect(self.entry_auth_data)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Авторизация"))
        self.lbl_login.setText(_translate("Form", "Логин:"))
        self.lbl_password.setText(_translate("Form", "Пароль:"))
        self.btn_enter.setText(_translate("Form", "Войти"))
        self.btn_registration.setText(_translate("Form", "Регистрация"))

    def entry_auth_data(self):
        login = self.lineE_login.text()
        password = self.lineE_password.text()
        if not login or not password:
            self.show_error_message("Ошибка", "Пожалуйста, введите корректное число.")
        else:
            self.accept()

    def show_error_message(self, title, message):
        dlg = QMessageBox()
        dlg.setWindowTitle("Ошибка!")
        dlg.setText("Вы неправильно ввели данные!")
        button = dlg.exec()

        if button == QMessageBox.StandardButton.Ok:
            print("OK!")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Auth_form()
    ui.setupUi(Form)
    Form.show()

    if ui.exec() == QDialog.accepted:  # Проверяем, был ли диалог принят
        print("Данные успешно прошли")
    sys.exit(app.exec())
