# Form implementation generated from reading ui file 'form_for_create_lesson_object.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt6.QtWidgets import QFileDialog, QMessageBox, QDialog, QTreeWidget
from PyQt6 import QtCore, QtGui, QtWidgets



class Window_lesson_management(QDialog):
    def __init__(self, treeWidget):
        super().__init__()
        self.treeWidget= treeWidget
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setGeometry(500, 500, 400, 50)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_create_theory = QtWidgets.QPushButton(parent=Form)
        self.btn_create_theory.setObjectName("btn_creat_theority")
        self.horizontalLayout.addWidget(self.btn_create_theory)
        self.btn_create_test = QtWidgets.QPushButton(parent=Form)
        self.btn_create_test.setObjectName("btn_create_test")
        self.horizontalLayout.addWidget(self.btn_create_test)
        self.btn_upload_file = QtWidgets.QPushButton(parent=Form)
        self.btn_upload_file.setObjectName("btn_upload_file")
        self.horizontalLayout.addWidget(self.btn_upload_file)
        self.btn_delete_lesson = QtWidgets.QPushButton(parent=Form)
        self.btn_delete_lesson.setObjectName("btn_delete_lesson")
        self.horizontalLayout.addWidget(self.btn_delete_lesson)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.btn_create_theory.clicked.connect(self.open_window_for_write_theory)
        self.btn_create_test.clicked.connect(self.open_window_for_write_test)
        self.btn_upload_file.clicked.connect(self.upload_file)
        self.btn_delete_lesson.clicked.connect(self.delete_lesson)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_create_theory.setText(_translate("Form", "Написать теорию"))
        self.btn_create_test.setText(_translate("Form", "Создать тест"))
        self.btn_upload_file.setText(_translate("Form", "Загрузить готовый файл"))
        self.btn_delete_lesson.setText(_translate("Form", "Удалить урок"))

    def open_window_for_write_theory(self):
        ...

    def open_window_for_write_test(self):
        ...

    def upload_file(self):
        # Открываем диалог выбора файла
        file_name, _ = QFileDialog.getOpenFileName(self, "Выберите файл", "", "Все файлы (*)")
        if file_name:
            QMessageBox.information(self, "Информация", f"Вы выбрали файл: {file_name}")

    def delete_lesson(self):
        # Пытаюсь удалить потомка у родителя в qtreewidget из Main_Window_UI
        # selected_items = self.treeWidget.selectedItems()

        ...

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Сhoose_when_creating_course()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
