# Form implementation generated from reading ui file 'Главное окно c tabWidget.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QLabel

from logic import Logic

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1125, 735)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1121, 691))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(40, 50))
        self.tabWidget.setElideMode(QtCore.Qt.TextElideMode.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_image_account = QtWidgets.QWidget()
        self.tab_image_account.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tab_image_account.setAutoFillBackground(False)
        self.tab_image_account.setStyleSheet("")
        self.tab_image_account.setObjectName("tab_image_account")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI/icons/For Left bar/profile-anonymous2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_image_account, icon, "")
# tab_home
        self.tab_home = QtWidgets.QWidget()
        self.tab_home.isActiveWindow()
        self.tab_home.setObjectName("tab_home")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("UI/icons/For Left bar/Домой.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_home, icon1, "")
        self.tabWidget.currentChanged.connect(self.define_tab)

    # GUI in tab
        self.header_txt = QLabel("Курсы", MainWindow)
        self.header_txt.setGeometry(100, 20, 100, 50)
        self.header_txt.hide()
# tab_my_courses
        self.tab_my_courses = QtWidgets.QWidget()
        self.tab_my_courses.setObjectName("tab_my_courses")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("UI/icons/For Left bar/Курс.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_my_courses, icon2, "")

# tab_create_cource
        self.tab_create_cource = QtWidgets.QWidget()
        self.tab_create_cource.setObjectName("tab_create_cource")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("UI/icons/For Left bar/Создание курса.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_create_cource, icon3, "")

        self.tab_my_students = QtWidgets.QWidget()
        self.tab_my_students.setObjectName("tab_my_students")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("UI/icons/For Left bar/Учетные записи.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_my_students, icon4, "")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1125, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def define_tab(self, index):
        self.clear_all_tabs_gui()
        if index == 1:
            self.display_home_widget()
        elif index == 2:
            print("This is other")

    def display_home_widget(self):
        self.header_txt.show()

    def clear_all_tabs_gui(self):
        self.header_txt.hide()

        # self.combobox_filters = QComboBox()
        # self.combobox_filters.addItems(["Все", "Популярные", "Новинки"])
        # self.lineedit_search = QLineEdit()
        # self.button_search = QPushButton("Поиск")
        # self.table_view = QTableView()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
